### ISSUE TITLE
IntelliJ Ultimate 2018.3.1 support

### ISSUE THREAD

**Issue by borgstrom** [xmonader/sercapnp#6]
Hi @xmonader 👋 

Are you still maintaining this plugin?

When I try to install via the Plugins preferences UI it redirects to a GitHub release that doesn't exist, and throws an error:

<img width="1005" alt="screen shot 2018-12-18 at 4 26 57 pm" src="https://user-images.githubusercontent.com/1594130/50191252-e1c21180-02e1-11e9-9b67-6eae14aacd39.png">

<img width="953" alt="screen shot 2018-12-18 at 4 27 19 pm" src="https://user-images.githubusercontent.com/1594130/50191262-e686c580-02e1-11e9-963a-15db8aaa3490.png">

When I checkout the sources and the build the jar myself I get:

<img width="417" alt="screen shot 2018-12-18 at 4 27 39 pm" src="https://user-images.githubusercontent.com/1594130/50191274-f4d4e180-02e1-11e9-9ee5-d7d3eea0ac77.png">

I am running:

```
IntelliJ IDEA 2018.3.1 (Ultimate Edition)
Build #IU-183.4588.61, built on December 4, 2018
JRE: 1.8.0_152-release-1343-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

**Comment by xmonader** [comment]
Hi @borgstrom! Sadly I don't use intellij anymore

I applied quick fix on source it should be working fine

![screenshot_2018-12-19_08-17-22](https://user-images.githubusercontent.com/64129/50202319-63f41980-0366-11e9-8d9e-a46d82637356.png)
I'll update the releases in the repo and in intellij center! have a great day

**Comment by borgstrom** [comment]
Thanks for the response!

I just downloaded the 1.4 zip, but I still get the same error as when I built the jar locally myself:

<img width="422" alt="screen shot 2018-12-19 at 8 05 33 am" src="https://user-images.githubusercontent.com/1594130/50232007-e5e34300-0364-11e9-80a5-a0b1447a7266.png">

Let me know if I can provide any other info.
